# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER chiwd

# 挂载目录
VOLUME /home/project
# 创建目录
RUN mkdir -p /home/project
# 指定路径
WORKDIR /home/project
# 复制jar文件到路径
COPY ./jar/yudao-module-infra-biz.jar /home/project/yudao-module-infra-biz.jar
COPY ./jar/application.yaml /home/project/application.yaml
COPY ./jar/application-prod.yaml /home/project/application-prod.yaml
COPY ./jar/bootstrap.yaml /home/project/bootstrap.yaml
COPY ./jar/bootstrap-prod.yaml /home/project/bootstrap-prod.yaml
COPY ./jar/logback-spring.xml /home/project/logback-spring.xml
# 启动文件服务
ENTRYPOINT ["java","-server","-Xms512m","-Xmx512m","-XX:+HeapDumpOnOutOfMemoryError","-XX:HeapDumpPath=heapError","-jar","yudao-module-infra-biz.jar","--spring.profiles.active=prod"]