# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER chiwd

# 挂载目录
VOLUME /home/fis
# 创建目录
RUN mkdir -p /home/project
# 指定路径
WORKDIR /home/fis
# 复制jar文件到路径
COPY ./jar/fis-module-system-biz.jar /home/fis/fis-module-system-biz.jar
COPY ./jar/application.yaml /home/fis/application.yaml
COPY ./jar/application-prod.yaml /home/fis/application-prod.yaml
COPY ./jar/bootstrap.yaml /home/fis/bootstrap.yaml
COPY ./jar/bootstrap-prod.yaml /home/fis/bootstrap-prod.yaml
COPY ./jar/logback-spring.xml /home/fis/logback-spring.xml
# 启动系统服务
ENTRYPOINT ["java","-server","-Xms512m","-Xmx512m","-XX:+HeapDumpOnOutOfMemoryError","-XX:HeapDumpPath=heapError","-jar","fis-module-system-biz.jar","--spring.profiles.active=prod"]